config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "videos#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, except: %i[show new create]
  resources :videos do
    post :increment_view, on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: %i[common admin]
  validates_presence_of :email, uniqueness: true
  has_many :videos
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :user

  validates :title, :views, :url, presence: true
  validate :valid_url?

  default_scope { order("views DESC") }

  def valid_url?
    raise_url_error unless url.present? && url.end_with?(".m3u8")
    uri = URI.parse(url)
    raise_url_error unless uri.is_a?(URI::HTTP) && !uri.host.nil?
  rescue URI::InvalidURIError
    raise_url_error
  end

  def raise_url_error()
    errors.add(:url, "must be a valid url and has '.m3u8' extension")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: :show
  protect_from_forgery with: :exception
  respond_to :html

  def show_error
    flash[:alert] = "There's something wrong. Please, try again."
    render :new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  expose(:users) { User.all.includes(:videos) }
  expose(:user)

  def index
  end

  def edit
  end

  def update
    if user.update(user_attributes)
      flash[:notice] = "User has been updated!"
      respond_with user, location: users_path
    else
      show_error
    end
  end

  def show
  end

  def destroy
    flash[:notice] = "User has been deleted!"
    user.destroy
    respond_with user, location: users_path
  end

  private
  def user_attributes
    user.attributes = params.require(:user).permit(%i[id email role])
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  expose(:videos) {  (current_user.admin? ? Video.all : Video.where(user_id: current_user.id)).includes(:user) }
  expose(:video)

  def index
  end

  def new
  end

  def create
    video.attributes = video_attributes
    if video.save
      flash[:notice] = "The video #{video.title} has been created!"
      respond_with video, location: videos_path
    else
      show_error
    end
  end

  def edit
  end

  def update
    if video.update(video_attributes)
      flash[:notice] = "The video #{video.title} has been updated!"
      respond_with video, location: videos_path
    else
      show_error
    end
  end

  def show
  end

  def destroy
    flash[:notice] = "The video #{video.title} has been deleted!"
    video.destroy
    respond_with video, location: videos_path
  end

  def increment_view
    video.increment!(:views)
  end

  private

  def video_attributes
    params.require(:video).permit(%i[id user_id title url])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_menu.html.erb
<div class="collapse navbar-collapse">
  <% if current_user.admin? %>
    <ul class="nav navbar-nav">
      <li><%= link_to "Users", users_path %></li>
    </ul>
  <% end %>
  <ul class="nav navbar-nav navbar-right">
    <li>
      <%= link_to "Account Config", edit_user_path(current_user.id) %>
    </li>
    <li>
      <%= link_to "Logout", [:destroy, :user, :session], method: :delete,
                  data: { confirm: "Are you sure?" } %>
    </li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Challenge</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <header>
        <div class="navbar navbar-default">
          <div class="container-fluid">
            <div class="navbar-header">
              <%= link_to "Home", :root, class: "navbar-brand" %>
            </div>
            <%= render "layouts/menu" %>
          </div>
        </div>
      </header>
    <% end %>
    <div class="container">
      <div class="col-md-12 text-center">
        <% if notice.present? %>
          <p class="alert alert-success"><%= notice %></p>
        <% elsif alert.present? %>
          <p class="alert alert-danger"><%= alert %></p>
        <% end %>
      </div>
      <%= yield %>
    </div>
    </div>
  </body>
</html>

app/views/users/_form.html.erb
<div class="page-header">
  <h1>Users's Info</h1>
</div>

<%= simple_form_for user do |f| %>
  <div class="row">
    <div class="col-md-6">
      <%= f.input :email, input_html: { autofocus: true }, disabled: user != current_user %>
      <% if current_user.admin? %>
        <%= f.input :role, as: :radio_buttons, collection: User.roles.map { |role| [role.first.capitalize, role.first] }, checked: user.new_record? ? "common" : user.role, item_wrapper_class: "radio-inline" %>
      <% end %>
      <% if user == current_user %>
        <%= f.input :password %>
        <%= f.input :password_confirmation %>
      <% end %>
    </div>
  </div>
  <hr>
  <%= submit_tag "Submit", class: "button btn btn-primary", data: { disable_with: "Submiting" } %>
  <%= link_to "Cancel", :back, class: "btn btn-default" %>
<% end %>

app/views/users/_user.html.erb
<tr>
  <td class="col-md-3">
    <%= user.email %>
  </td>
  <td class="col-md-3">
    <%= user.videos.size %>
  </td>
  <td class="col-md-3">
    <%= user.role %>
  </td>
  <td class="col-md-3">
    <div class="btn-toolbar pull-right">
      <%= link_to "Edit", edit_user_path(user.id), class: "btn btn-sm btn-primary" %>
      <%= link_to "Delete", user_path(user.id), class: "btn btn-sm btn-danger", method: :delete, data: { confirm: "This will be permanent, are you sure?" } %>
    </div>
  </td>
</tr>

app/views/users/edit.html.erb
<%= render "form" %>

app/views/users/index.html.erb
<div class="page-header">
  <h1>Users</h1>
</div>
<div class="table-responsive">
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Email</th>
        <th>Videos Quantity</th>
        <th>Role</th>
        <th></th>
        
    <tbody>
      <% users.each do |user|  %>
        <%= render "user", user: user %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/videos/_form.html.erb
<div class="page-header">
  <h1>Video's Info</h1>
</div>

<%= simple_form_for video do |f| %>
  <div class="row">
    <div class="col-md-6">
      <%= f.hidden_field :user_id, value: video.user_id || current_user.id %>
      <%= f.input :title, input_html: { autofocus: true } %>
      <%= f.input :url %>

    </div>
  </div>
  <hr>
  <%= submit_tag "Submit", class: "button btn btn-primary", data: { disable_with: "Submiting" } %>
  <%= link_to "Cancel", :back, class: "btn btn-default" %>
<% end %>

app/views/videos/_video.html.erb
<tr>
  <td class="col-md-3">
    <%= video.title %>
  </td>
  <td class="col-md-3">
    <%= video.views %>
  </td>
  <% if current_user.admin? %>
    <td class="col-md-3">
      <%= video.user.email %>
    </td>
  <% end %>
  <td class="col-md-3">
    <div class="btn-toolbar pull-right">
      <%= link_to "Watch", video_path(video.id), class: "btn btn-sm btn-primary" %>
      <%= link_to "Edit", edit_video_path(video.id), class: "btn btn-sm btn-primary" %>
      <%= link_to "Delete", video_path(video.id), class: "btn btn-sm btn-danger", method: :delete, data: { confirm: "This will be permanent, are you sure?" } %>
    </div>
  </td>
</tr>

app/views/videos/index.html.erb
<div class="page-header">
  <h1>Videos</h1>
</div>

<div class="col-md-4">
  <%= link_to "Add new", new_video_path, class: "btn btn-success" %>
</div>
<br>

<% unless videos.blank? %>
  <br>
  <div class="table-responsive">
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>Title</th>
          <th>Views</th>
          <% if current_user.admin? %>
            <th>Creator</th>
          <% end %>
          <th></th>
          
      <tbody>
        <% videos.each do |video|  %>
          <%= render "video", video: video %>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/videos/new.html.erb
<%= render "form" %>

app/views/videos/show.html.erb
<div class="page-header">
  <h1><%= video.title %></h1>
</div>

<div class="cd-md-12">
  <video id="video-tag" class="video-js vjs-default-skin" controls autoplay
   width="640" height="360" data-url="<%= increment_view_video_path(video.id) %>">
    <source
     src="<%= video.url %>"
     type="application/x-mpegURL">
  </video>
  <p>Viewed <%= video.views %> times</p>
</div>